import { images } from '../constants';
const News = [
    { id: 1, 
      date: "24 August 2022",
      image: images.homeNews1,
      url: "https://novafusion.my/development/PWA-test/",
      item: "Lorem ipsum dolor",
    },
    { id: 2, 
      date: "24 August 2022",
      image: images.homeNews2,
      url: "https://novafusion.my/development/PWA-test/",
      item: "Lorem ipsum dolor",
    },
    { id: 3, 
      date: "24 August 2022",
      image: images.homeNews3,
      url: "https://novafusion.my/development/PWA-test/",
      item: "Lorem ipsum dolor",
    },
    { id: 4, 
      date: "24 August 2022",
      image: images.homeNews3,
      url: "https://novafusion.my/development/PWA-test/",
      item: "Lorem ipsum dolor",
    },
    { id: 5, 
      date: "24 August 2022",
      image: images.homeNews3,
      url: "https://novafusion.my/development/PWA-test/",
      item: "Lorem ipsum dolor",
    },
    { id: 6, 
      date: "24 August 2022",
      image: images.homeNews3,
      url: "https://novafusion.my/development/PWA-test/",
      item: "Lorem ipsum dolor",
    },
  ];

  export default News;