import { images } from '../constants';
const News = [
    { id: 1, 
      date: "24 August 2022",
      image: images.homeNews1,
      url: "https://nyuad.nyu.edu/en/news/latest-news/science-and-technology/2022/august/ewa-startad.html",
      item: "Tamkeen and startAD Launch Emirati Women Achievers Campaign in Celebration of Emirati Women's Day",
    },
    { id: 2, 
      date: "24 August 2022",
      image: images.homeNews2,
      url: "https://www.khaleejtimes.com/uae/emirati-womens-day-coffee-table-book-honouring-51-female-achievers-launched?amp=1",
      item: "Emirati Women's Day: Commemorative book honouring 51 female achievers launched",
    },
    { id: 3, 
      date: "24 August 2022",
      image: images.homeNews3,
      url: "https://nyuad.nyu.edu/en/news/latest-news/science-and-technology/2022/august/ewa-startad.html",
      item: "Tamkeen and startAD Launch Emirati Women Achievers Campaign in Celebration of Emirati Women's Day",
    },
    { id: 4, 
      date: "24 August 2022",
      image: images.homeNews3,
      url: "/",
      item: "Lorem ipsum dolor",
    },
    { id: 5, 
      date: "24 August 2022",
      image: images.homeNews3,
      url: "/",
      item: "Lorem ipsum dolor",
    },
    { id: 6, 
      date: "24 August 2022",
      image: images.homeNews3,
      url: "/",
      item: "Lorem ipsum dolor",
    },
  ];

  export default News;